version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - copyloopvar
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - forbidigo
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - revive
    - sloglint
    - staticcheck
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl_v5
    - zerologlint
  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          arguments:
            - 20
        - name: flag-parameter
          disabled: true
        - name: function-length
          arguments:
            - 52
            - 468
        - name: import-shadowing
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: struct-tag
          disabled: true
    depguard:
      rules:
        all:
          allow:
            - $gostd
            - github.com/rkitindi-kr/dynatrace-bootstrapper
            - github.com/go-logr/logr
            - github.com/go-logr/zapr
            - github.com/pkg/errors
            - github.com/spf13/afero
            - github.com/spf13/cobra
            - github.com/stretchr/testify
            - go.uber.org/zap
            - go.uber.org/zap/zapcore
            - golang.org/x/sys/unix
            - path/filepath
            - encoding/json
            - io
            - os
            - testing
            - maps
            - strings
            - sort
            - bufio
            - regexp
            - errors
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - perfsprint
          - wsl
        path: _(test|gen)\.go
